name: Build and Deploy Code

#runner: github-hosted runner, a runner is a machine that runs your code

#jobs: jobs are the tasks that are executed in the runner

#steps: steps are the commands that are executed in the runner

#runs-on: the machine that runs the code, can be ubuntu-latest, windows-latest, 
#macos-latest, or all of them, right now we are using ubuntu-latest as our production environment is ubuntu


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0142
      POSTGRES_DB: fastapi-DB
      # POSTGRES_HOST: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      SECRET_KEY: 8fcedbda9a4794e0dfaac1e3c074a819577b75629c0db631efc09d6545506abe
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:0142@postgres:5432/fastapi-DB
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        run: |
          pip install pytest
          pip install requests
          pytest
